
package:
  name: r-recommended
  version: {{ r_base }}

build:
  noarch: generic
  number: 1004

requirements:
  host:
      - r-base
  run:
    - r-base
    - r-boot
    - r-class
    - r-cluster
    - r-codetools
    - r-foreign
    - r-kernsmooth
    - r-lattice
    - r-mass
    - r-matrix
    - r-mgcv
    - r-nlme
    - r-nnet
    - r-rpart
    - r-spatial
    - r-survival

# test to force the test env creation
# if any dependency is missing the test env creation will fail
test:
  commands:
    - $R -e "library('MASS')"           # [not win]
    - "\"%R%\" -e \"library('MASS')\""  # [win]

about:
  home: http://www.r-project.org/
  license: GPL-3.0
  summary: 'R is a free software environment for statistical computing and graphics.'

extra:
  recipe-maintainers:
    - conda-forge/r
