appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: wnCjUJtyrJvweA2Glb+W/GmV7RYGgZZwoiogSXriByrPgHTzPd4yrsGDItpkOPiiSl+qIK0F8aRw8zAF+6mfSpBxruHNEwF0BLfD2qBl2pkG2GktWi2H9/pQF1/twjjQ5dW4sYKdBv2iotCLOm6QJSnltHx2+zUff89Y5/aOHXA6H0XgCBj3TtcX9Cn7qZJGbkEnbBwMv7DVioXlW9wTKsI0tR05qSEi+HTa4SRhi06SftMj1X3d9or+k7zoPmKdznpT9BZAN1qQu+kch4NdNQeQHfW9tY4EXcIjAlDDGxw6ObahYCBl/efaNhKbafiZn8Iajm5jmz3lQK1xFjgI+Gv5GZ0aEshtg6a8Hq7NxzNQyvdY3/4z4GmeGHzEf9vHLlX2nSBrB2YouCrOQ6Sr/TQlQ3FbQ+QihLcABDBxoismJY92YmdY4cDIVVtaXLHhZxNvGrrc2IW2d3fXyTPo5G2ZwOW4NtQaaNxxUVD1K/PQuSHVIzereMbGL/6MRyQ9Wdh01KSvt3fUOF7Jk7j1tPWgDUertS6Vlq5Rvc/zYz2BZTvlMePq6CfeKWEQSn82wshnqzAtC4bs4lvOu6n4ocD5AVO+huOKrSxMd8r4+/X2IMV1qgy0/p1LLdbvRyfBreS5hDXpelDo+RCtVfp9AV4YRLAZ7ukuJoNMNGHY4/s=
